name: Get Yougile Task ID
inputs:
  repository:
    description: Repository name
    required: true
  github-token:
    description: Github Token to access to Github Issues
    required: true
  issue-number:
    description: Issue where to be find Yougile Task ID
    required: true
outputs:
  id:
    description: Yougile Task ID
    value: ${{ steps.task.outputs.id }}
runs:
  using: composite
  steps:
    - id: task
      shell: bash
      run: |
        ID="$(gh issue view ${{ inputs.issue-number }} --comments \
        | grep 'YouGile task ID' \
        | sed -E 's/YouGile task ID: `([^`]*)`/\1/g')"
        echo "id=$ID" > $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        GH_REPO: ${{ inputs.repository }}

