name: YouGile Tasks
on:
  issues:
    types: [opened, reopened, closed, edited, labeled]
jobs:
  create-yougile-task:
    name: Create task
    if: github.event.action == 'opened'
    runs-on: ubuntu-22.04
    permissions:
      issues: write
    steps:
      - id: create-task
        run: |
          ID="$(
          curl -sS --request POST \
            --url https://ru.yougile.com/api-v2/tasks \
            --header 'Authorization: Bearer ${{ secrets.YOUGILE_API_KEY }}' \
            --header 'Content-Type: application/json' \
            --data '{
              "title": ${{ toJson(github.event.issue.title) }},
              "columnId": ${{ toJson(secrets.YOUGILE_COLUMN_ID) }},
              "description": "<a href=\"https://github.com/${{ github.repository }}/issues/${{ github.event.issue.number }}\">Показать в Github</a>"
            }' | jq -r '.id'
          )"
          echo "id=$ID" > $GITHUB_OUTPUT
      - run: |
          gh issue comment ${{ github.event.issue.number }} \
            --body "YouGile task ID: \`${{ steps.create-task.outputs.id }}\`"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
  update-complete-status:
    name: Update complete status
    if: github.event.action == 'closed' || github.event.action == 'reopened'
    runs-on: ubuntu-22.04
    steps:
      - id: task
        uses: actions/yougile-task-id
        with:
          issue-number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/yougile-esit-task
        with:
          task-body: |
            { "completed": ${{ github.event.action == 'closed' }} }
          task-id: ${{ steps.task.outputs.id }}
          yougile-api-key: ${{ secrets.YOUGILE_API_KEY }}
  update-title:
    name: Update title
    if: github.event.action == 'edited'
    runs-on: ubuntu-22.04
    steps:
      - id: task
        uses: actions/yougile-task-id
        with:
          issue-number: ${{ github.event.issue.number }}
          repository: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/yougile-esit-task
        with:
          task-body: |
            { "title": ${{ toJson(github.event.issue.title) }} }
          task-id: ${{ steps.task.outputs.id }}
          yougile-api-key: ${{ secrets.YOUGILE_API_KEY }}
